### ISSUE TITLE
Class not found hatası

### ISSUE THREAD

**Issue by burakaktna** [yasinkuyu/omnipay-paytr#1]
Merhablar Yasin bey, Laravel frameworkü ile kodlanmış projemde kullanmak için vendor altında omnipay klasörüne dosyaları clone ettim. Şu an da Omnipay::create('PayTR') şeklinde kullanmaya çalıştığımda class not found hatası döndürüyor.

**Comment by yasinkuyu** [comment]
vendor klasörüne clone yerine vendor klasörünün olduğu dizinde aşağıdaki komutu çalıştırabilir msiniz?

 composer require yasinkuyu/omnipay-paytr
